#************************* GAAP-BP v.1.0 config file *************************#
											
#********** MIT LICENSE - Copyright © 2022 Gian M.N. Benucci, Ph.D. **********#
#*********************** email: benucci[at]msu[dot]edu ***********************#

echo "====> Reading GAAP-BP v. 1.0 config.yaml"
project_dir="/mnt/home/benucci/GAAP-BP"
cd $project_dir/rawdata/

# Databases
NCBI_nt="/mnt/research/ShadeLab/Benucci/databases/ncbi_nt1121"
kraken2_db="/mnt/research/ShadeLab/Benucci/databases/kraken2_db/"
minikraken2_db="/mnt/research/ShadeLab/Benucci/databases/minikraken2_db/"
platon_db="/mnt/research/ShadeLab/Benucci/databases/platon_db/db/"
mash_plsdb="/mnt/research/ShadeLab/Benucci/databases/plasmid_db/plsdb.msh"
mash_plsdb_meta="/mnt/research/ShadeLab/Benucci/databases/plasmid_db/plsdb.tsv"
busco_db="/mnt/research/ShadeLab/Benucci/databases/busco_db1121/bacteria_odb10"
phix_db="/mnt/research/ShadeLab/Benucci/databases/phix_index/my_phix"
bakta_db="/mnt/research/ShadeLab/Benucci/databases/bakta_db/db"
#dmnd_bac="/mnt/research/ShadeLab/Benucci/databases/emapperdb/eggdb_bacteria.dmnd"

# Run options
STRING=ccs
MASH=yes
BAKTA=no
EGGNOG=yes
CHROMOSOMES=5

# PATHs
export GTDBTK_DATA_PATH=/mnt/research/ShadeLab/Benucci/databases/gtdb_tk/release207_v2
export EGGNOG_DATA_DIR=/mnt/research/ShadeLab/Benucci/databases/emapperdb/

#NOTEs
# * The larger kraken2 database, the better. For genome isolates the minikraken 
# should be ok. 

#*******************************************************************************#
